### ISSUE TITLE
After click submit button modal lose style

### ISSUE THREAD

**Issue by rogeriocdluiz** [optiflows/django-modalview#17]
trying django-modalview using project examples the modal is showed but after click in submit button modal loose style.

![modal1](https://cloud.githubusercontent.com/assets/5632379/15259785/af32f666-1929-11e6-8bde-76d517168edb.png)

![modal2](https://cloud.githubusercontent.com/assets/5632379/15259789/b442e56c-1929-11e6-93a1-d918f94b3b73.png)

The view django_modal_view.js is presenting the following error on line 67:

`TypeError: this.element.ajaxForm is not a function this.element.ajaxForm`

**Comment by vamonte** [comment]
Hi @rogeriocdluiz , 

I think you have not include the static file named  'django_modalview/js/jquery.form.js' in your template.
May you show us your code?

**Comment by rogeriocdluiz** [comment]
Thank You. This is the problem! Solved!
