### ISSUE TITLE
Change submit and close buttons labels

### ISSUE THREAD

**Issue by rogeriocdluiz** [optiflows/django-modalview#21]
How to change the submit and close buttons labels. Default is SEND and CLOSE.

I tested self.submit_button = "Enviar" and self.close_button = "Fechar" but buttons disappeared.

**Comment by vamonte** [comment]
These buttons are instances of the ModalButton class (https://github.com/optiflows/django-modalview/blob/master/django_modalview/generic/component.py).
You just have to set the attribute named value.

```python
  self.submit_button.value = "Enviar"
```

**Comment by rogeriocdluiz** [comment]
Thank you!
